version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    expose:
      - 5000
    ports:
      - "5000:5000"
    environment:
      - HOST=0
      - PORT=5000
      - DEBUG
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    expose:
      - 4200
    ports:
      - "4200:4200"